# Generated by Django 5.2.6 on 2026-01-27 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_profile_image_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('accept_terms', models.BooleanField(default=False)),
                ('subscribe_newsletter', models.BooleanField(default=False)),
                ('trial_days', models.IntegerField(default=0)),
                ('trial_start_date', models.DateTimeField(blank=True, null=True)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Email Verified'), ('active', 'Active Account'), ('trial_expired', 'Trial Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['-registered_at'], name='accounts_re_registe_60b06c_idx'), models.Index(fields=['status', '-registered_at'], name='accounts_re_status_0438b7_idx'), models.Index(fields=['email'], name='accounts_re_email_563cb3_idx')],
            },
        ),
    ]
