# Generated by Django 5.2.6 on 2026-01-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='intent',
            field=models.CharField(blank=True, choices=[('14_day_trial', '14 Day Trial'), ('demo', 'Request Demo'), ('become_customer', 'Become Customer'), ('more_info', 'More Information'), ('contact_sales', 'Contact Sales')], max_length=50, null=True),
        ),
    ]
