# Generated by Django 4.2.28 on 2026-02-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_teaminvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Administrator'), ('pm', 'Project Manager'), ('program_manager', 'Program Manager'), ('contibuter', 'Contibuter'), ('reviewer', 'Reviewer'), ('guest', 'Guest')], default='superadmin', max_length=100),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('pm', 'Project Manager'), ('program_manager', 'Program Manager'), ('admin', 'Admin')], default='guest', max_length=20),
        ),
    ]
