# Generated by Django 4.2.28 on 2026-02-18 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0004_skills_system_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_nl', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('description_nl', models.TextField(blank=True)),
                ('passing_score', models.IntegerField(default=80)),
                ('time_limit', models.IntegerField(default=45, help_text='Time limit in minutes')),
                ('max_attempts', models.IntegerField(default=3)),
                ('questions', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('passed', models.BooleanField(default=False)),
                ('answers', models.JSONField()),
                ('time_taken', models.IntegerField()),
                ('attempt_number', models.IntegerField(default=1)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_nl', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='academy/resources/')),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=500)),
                ('answer_text_nl', models.CharField(blank=True, max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('passed', models.BooleanField(default=False)),
                ('answers', models.JSONField()),
                ('time_taken', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_text_nl', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('multiple_select', 'Multiple Select')], default='multiple_choice', max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('explanation_nl', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issued_at']},
        ),
        migrations.RemoveConstraint(
            model_name='lessonskillmapping',
            name='unique_lesson_skill',
        ),
        migrations.RemoveConstraint(
            model_name='userskill',
            name='unique_user_skill',
        ),
        migrations.RemoveIndex(
            model_name='skillactivity',
            name='idx_user_activity_date',
        ),
        migrations.RemoveIndex(
            model_name='userskill',
            name='idx_user_skill_points',
        ),
        migrations.AddField(
            model_name='certificate',
            name='exams_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificate',
            name='lessons_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificate',
            name='practice_submitted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificate',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='certificates/qr/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='quizzes_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificate',
            name='simulations_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificate',
            name='skills_data',
            field=models.JSONField(blank=True, default=dict, help_text='Skills breakdown at certification time'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='total_score',
            field=models.IntegerField(default=0, help_text='Overall course score percentage'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='verification_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='skillactivity',
            name='activity_type',
            field=models.CharField(choices=[('lesson_complete', 'Lesson Completed'), ('quiz_pass', 'Quiz Passed'), ('simulation_correct', 'Simulation Correct'), ('practice_submit', 'Practice Submitted')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='lessonskillmapping',
            unique_together={('lesson_id', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('user', 'skill')},
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_number'], name='academy_cer_certifi_0ff74b_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['verification_code'], name='academy_cer_verific_9d29d9_idx'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academy.courselesson'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='academy.courselesson'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='academy.quizquestion'),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academy.courselesson'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='academy.exam'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academy.course'),
        ),
        migrations.AddField(
            model_name='exam',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academy.coursemodule'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'lesson'], name='academy_qui_user_id_4d3a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['user', 'exam'], name='academy_exa_user_id_bfceb9_idx'),
        ),
    ]
