# Generated by Django 4.2.28 on 2026-02-21 15:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_lesson_visual_management'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-started_at']},
        ),
        migrations.RemoveIndex(
            model_name='quizattempt',
            name='academy_qui_user_id_4d3a1a_idx',
        ),
        migrations.RenameIndex(
            model_name='lessonvisual',
            new_name='academy_les_status_96fc68_idx',
            old_name='academy_les_status_idx',
        ),
        migrations.RenameIndex(
            model_name='lessonvisual',
            new_name='academy_les_lesson__8aaadb_idx',
            old_name='academy_les_lesson_idx',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='time_taken',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='user',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='enrollment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='academy.enrollment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='max_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
