# Generated by Django 4.2.28 on 2026-02-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_practiceassignment_practicesubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonvisual',
            name='ai_intent',
            field=models.TextField(blank=True, help_text='AI-detected learning intent', null=True),
        ),
        migrations.AlterField(
            model_name='lessonvisual',
            name='ai_methodology',
            field=models.TextField(blank=True, help_text='AI-detected methodology', null=True),
        ),
        migrations.AlterField(
            model_name='lessonvisual',
            name='visual_id',
            field=models.CharField(help_text='Visual identifier (e.g., project-definition, timeline, stakeholder)', max_length=200),
        ),
    ]
