# Generated by Django 4.2.28 on 2026-02-08 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_alter_portfolio_company'),
        ('programs', '0002_programbudget_programbudgetcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='governance.portfolio'),
        ),
    ]
