# Generated by Django 4.2.28 on 2026-02-08 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_program_portfolio'),
        ('governance', '0002_alter_portfolio_company'),
        ('projects', '0008_budgetcategory_budgetitem_projectbudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='governance.portfolio'),
        ),
        migrations.AddField(
            model_name='project',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_projects', to='programs.program'),
        ),
    ]
