import { useState, useEffect } from "react"; import { useParams } from "react-router-dom"; import { Card, CardContent } from "@/components/ui/card"; import { Button } from "@/components/ui/button"; import { Badge } from "@/components/ui/badge"; import { ProjectHeader } from "@/components/ProjectHeader"; import { usePageTranslations } from "@/hooks/usePageTranslations"; import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Loader2, Plus, ShieldCheck, CheckCircle2, XCircle, Pencil, Trash2 } from "lucide-react"; import { toast } from "sonner";
const BASE = (id: string) => `/api/v1/sixsigma/projects/${id}/sixsigma`;
const SixSigmaTollgate = () => { const { pt } = usePageTranslations(); const { id } = useParams<{ id: string }>(); const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [dialogOpen, setDialogOpen] = useState(false); const [editing, setEditing] = useState<any>(null); const [submitting, setSubmitting] = useState(false); const [form, setForm] = useState({ phase: "", reviewer: "", review_date: "", deliverables: "", findings: "", recommendations: "" }); const token = localStorage.getItem("access_token"); const headers: Record<string, string> = { Authorization: `Bearer ${token}` }; const jsonHeaders = { ...headers, "Content-Type": "application/json" };
  const fetchData = async () => { try { const r = await fetch(`${BASE(id!)}/tollgates/`, { headers }); if (r.ok) { const d = await r.json(); setItems(Array.isArray(d) ? d : d.results || []); } } catch (err) { console.error(err); } finally { setLoading(false); } }; useEffect(() => { fetchData(); }, [id]);
  const initTollgates = async () => { try { const r = await fetch(`${BASE(id!)}/tollgates/initialize/`, { method: "POST", headers: jsonHeaders }); if (r.ok) { toast.success("Tollgates geïnitialiseerd"); fetchData(); } } catch { toast.error("Initialiseren mislukt"); } };
  const openCreate = () => { setEditing(null); setForm({ phase: "", reviewer: "", review_date: "", deliverables: "", findings: "", recommendations: "" }); setDialogOpen(true); };
  const openEdit = (i: any) => { setEditing(i); setForm({ phase: i.phase || "", reviewer: i.reviewer || "", review_date: i.review_date?.split("T")[0] || "", deliverables: i.deliverables || "", findings: i.findings || "", recommendations: i.recommendations || "" }); setDialogOpen(true); };
  const handleSave = async () => { if (!form.phase) { toast.error("Phase verplicht"); return; } setSubmitting(true); try { const body: any = { ...form }; if (!form.review_date) delete body.review_date; const url = editing ? `${BASE(id!)}/tollgates/${editing.id}/` : `${BASE(id!)}/tollgates/`; const r = await fetch(url, { method: editing ? "PATCH" : "POST", headers: jsonHeaders, body: JSON.stringify(body) }); if (r.ok) { toast.success("Opgeslagen"); setDialogOpen(false); fetchData(); } else toast.error("Opslaan mislukt"); } catch { toast.error("Opslaan mislukt"); } finally { setSubmitting(false); } };
  const approve = async (tId: number) => { try { const r = await fetch(`${BASE(id!)}/tollgates/${tId}/approve/`, { method: "POST", headers: jsonHeaders }); if (r.ok) { toast.success("Goedgekeurd"); fetchData(); } } catch {} };
  const reject = async (tId: number) => { try { const r = await fetch(`${BASE(id!)}/tollgates/${tId}/reject/`, { method: "POST", headers: jsonHeaders }); if (r.ok) { toast.success("Afgekeurd"); fetchData(); } } catch {} };
  const handleDelete = async (tId: number) => { if (!confirm("Verwijderen?")) return; try { await fetch(`${BASE(id!)}/tollgates/${tId}/`, { method: "DELETE", headers }); fetchData(); } catch {} };
  const phaseColors: Record<string, string> = { define: "bg-blue-500", measure: "bg-green-500", analyze: "bg-yellow-500", improve: "bg-orange-500", control: "bg-red-500" };
  const statusColors: Record<string, string> = { pending: "bg-gray-100 text-gray-700", approved: "bg-green-100 text-green-700", rejected: "bg-red-100 text-red-700" };
  if (loading) return (<div className="min-h-full bg-background"><ProjectHeader /><div className="flex items-center justify-center py-20"><Loader2 className="h-8 w-8 animate-spin" /></div></div>);
  return (<div className="min-h-full bg-background"><ProjectHeader /><div className="p-6 space-y-6">
    <div className="flex items-center justify-between"><div className="flex items-center gap-3"><ShieldCheck className="h-6 w-6 text-amber-500" /><h1 className="text-2xl font-bold">Tollgate Reviews</h1><Badge variant="outline">{items.length}</Badge></div><div className="flex gap-2">{items.length === 0 && <Button variant="outline" onClick={initTollgates}>Initialize DMAIC</Button>}<Button onClick={openCreate} className="gap-2"><Plus className="h-4 w-4" /> {pt("Add")}</Button></div></div>
    {items.length === 0 ? <Card className="p-8 text-center"><ShieldCheck className="h-12 w-12 mx-auto text-muted-foreground mb-4" /><h3 className="text-lg font-semibold">No tollgate reviews yet</h3></Card> : (<div className="space-y-3">{items.map(i => (<Card key={i.id} className={i.status === "approved" ? "border-green-200" : i.status === "rejected" ? "border-red-200" : ""}><CardContent className="p-4"><div className="flex items-center justify-between mb-2"><div className="flex items-center gap-2"><div className={`h-6 w-6 rounded-full ${phaseColors[i.phase?.toLowerCase()] || "bg-gray-400"} flex items-center justify-center text-white text-xs font-bold`}>{i.phase?.charAt(0)}</div><span className="font-semibold">{i.phase}</span><Badge className={`text-xs ${statusColors[i.status] || ""}`}>{i.status}</Badge>{i.reviewer && <span className="text-xs text-muted-foreground">by {i.reviewer}</span>}</div><div className="flex gap-1">{i.status !== "approved" && <Button variant="outline" size="sm" onClick={() => approve(i.id)} className="gap-1 text-xs text-green-600"><CheckCircle2 className="h-3 w-3" /> Approve</Button>}{i.status !== "rejected" && <Button variant="outline" size="sm" onClick={() => reject(i.id)} className="gap-1 text-xs text-red-600"><XCircle className="h-3 w-3" /> Reject</Button>}<Button variant="ghost" size="sm" onClick={() => openEdit(i)}><Pencil className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="sm" onClick={() => handleDelete(i.id)}><Trash2 className="h-3.5 w-3.5 text-destructive" /></Button></div></div>{i.findings && <p className="text-sm"><strong>Findings:</strong> {i.findings}</p>}{i.recommendations && <p className="text-sm text-muted-foreground"><strong>Recommendations:</strong> {i.recommendations}</p>}</CardContent></Card>))}</div>)}
  </div>
  <Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogContent><DialogHeader><DialogTitle>{editing ? pt("Edit") : pt("Add")} Tollgate Review</DialogTitle></DialogHeader><div className="space-y-4"><div className="grid grid-cols-2 gap-4"><div className="space-y-2"><Label>Phase *</Label><Input value={form.phase} onChange={(e) => setForm({ ...form, phase: e.target.value })} placeholder="e.g. Define, Measure..." /></div><div className="space-y-2"><Label>Reviewer</Label><Input value={form.reviewer} onChange={(e) => setForm({ ...form, reviewer: e.target.value })} /></div></div><div className="space-y-2"><Label>Review Date</Label><Input type="date" value={form.review_date} onChange={(e) => setForm({ ...form, review_date: e.target.value })} /></div><div className="space-y-2"><Label>Deliverables</Label><textarea className="w-full min-h-[40px] px-3 py-2 border rounded-md bg-background" value={form.deliverables} onChange={(e) => setForm({ ...form, deliverables: e.target.value })} /></div><div className="space-y-2"><Label>Findings</Label><textarea className="w-full min-h-[40px] px-3 py-2 border rounded-md bg-background" value={form.findings} onChange={(e) => setForm({ ...form, findings: e.target.value })} /></div><div className="space-y-2"><Label>Recommendations</Label><textarea className="w-full min-h-[40px] px-3 py-2 border rounded-md bg-background" value={form.recommendations} onChange={(e) => setForm({ ...form, recommendations: e.target.value })} /></div><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setDialogOpen(false)}>{pt("Cancel")}</Button><Button onClick={handleSave} disabled={submitting}>{submitting && <Loader2 className="h-4 w-4 animate-spin mr-2" />}{pt("Save")}</Button></div></div></DialogContent></Dialog></div>);
};
export default SixSigmaTollgate;
