import { useState, useEffect } from "react"; import { useParams } from "react-router-dom"; import { Card, CardContent } from "@/components/ui/card"; import { Button } from "@/components/ui/button"; import { Badge } from "@/components/ui/badge"; import { ProjectHeader } from "@/components/ProjectHeader"; import { usePageTranslations } from "@/hooks/usePageTranslations"; import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Loader2, Plus, FlagTriangleRight, Pencil, Trash2, CheckCircle2 } from "lucide-react"; import { toast } from "sonner";
const BASE = (id: string) => `/api/v1/sixsigma/projects/${id}/sixsigma`;
const SixSigmaClosure = () => { const { pt } = usePageTranslations(); const { id } = useParams<{ id: string }>(); const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [dialogOpen, setDialogOpen] = useState(false); const [editing, setEditing] = useState<any>(null); const [submitting, setSubmitting] = useState(false); const [form, setForm] = useState({ title: "", actual_savings: "", lessons_learned: "", sustainability_plan: "", documentation_complete: false, training_complete: false }); const token = localStorage.getItem("access_token"); const headers: Record<string, string> = { Authorization: `Bearer ${token}` }; const jsonHeaders = { ...headers, "Content-Type": "application/json" };
  const fetchData = async () => { try { const r = await fetch(`${BASE(id!)}/closure/`, { headers }); if (r.ok) { const d = await r.json(); setItems(Array.isArray(d) ? d : d.results || []); } } catch (err) { console.error(err); } finally { setLoading(false); } }; useEffect(() => { fetchData(); }, [id]);
  const openCreate = () => { setEditing(null); setForm({ title: "", actual_savings: "", lessons_learned: "", sustainability_plan: "", documentation_complete: false, training_complete: false }); setDialogOpen(true); };
  const openEdit = (i: any) => { setEditing(i); setForm({ title: i.title || "", actual_savings: String(i.actual_savings || ""), lessons_learned: i.lessons_learned || "", sustainability_plan: i.sustainability_plan || "", documentation_complete: i.documentation_complete || false, training_complete: i.training_complete || false }); setDialogOpen(true); };
  const handleSave = async () => { if (!form.title) { toast.error("Titel verplicht"); return; } setSubmitting(true); try { const body: any = { ...form }; if (form.actual_savings) body.actual_savings = parseFloat(form.actual_savings); else delete body.actual_savings; const url = editing ? `${BASE(id!)}/closure/${editing.id}/` : `${BASE(id!)}/closure/`; const r = await fetch(url, { method: editing ? "PATCH" : "POST", headers: jsonHeaders, body: JSON.stringify(body) }); if (r.ok) { toast.success("Opgeslagen"); setDialogOpen(false); fetchData(); } else toast.error("Opslaan mislukt"); } catch { toast.error("Opslaan mislukt"); } finally { setSubmitting(false); } };
  const approve = async (cId: number) => { try { const r = await fetch(`${BASE(id!)}/closure/${cId}/approve/`, { method: "POST", headers: jsonHeaders }); if (r.ok) { toast.success("Project afgesloten"); fetchData(); } } catch {} };
  const handleDelete = async (cId: number) => { if (!confirm("Verwijderen?")) return; try { await fetch(`${BASE(id!)}/closure/${cId}/`, { method: "DELETE", headers }); fetchData(); } catch {} };
  if (loading) return (<div className="min-h-full bg-background"><ProjectHeader /><div className="flex items-center justify-center py-20"><Loader2 className="h-8 w-8 animate-spin" /></div></div>);
  return (<div className="min-h-full bg-background"><ProjectHeader /><div className="p-6 space-y-6">
    <div className="flex items-center justify-between"><div className="flex items-center gap-3"><FlagTriangleRight className="h-6 w-6 text-green-500" /><h1 className="text-2xl font-bold">Project Closure</h1></div><Button onClick={openCreate} className="gap-2"><Plus className="h-4 w-4" /> {pt("Add")}</Button></div>
    {items.length === 0 ? <Card className="p-8 text-center"><FlagTriangleRight className="h-12 w-12 mx-auto text-muted-foreground mb-4" /><h3 className="text-lg font-semibold">No closure reports yet</h3></Card> : (<div className="space-y-3">{items.map(i => (<Card key={i.id} className={i.status === "approved" ? "border-green-200 bg-green-50" : ""}><CardContent className="p-5"><div className="flex items-center justify-between mb-3"><div className="flex items-center gap-2"><span className="font-semibold text-lg">{i.title}</span><Badge variant={i.status === "approved" ? "default" : "secondary"} className="text-xs">{i.status || "draft"}</Badge></div><div className="flex gap-1">{i.status !== "approved" && <Button variant="outline" size="sm" onClick={() => approve(i.id)} className="gap-1 text-green-600"><CheckCircle2 className="h-3.5 w-3.5" /> Approve Closure</Button>}<Button variant="ghost" size="sm" onClick={() => openEdit(i)}><Pencil className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="sm" onClick={() => handleDelete(i.id)}><Trash2 className="h-3.5 w-3.5 text-destructive" /></Button></div></div>
      {i.actual_savings && <div className="mb-3 p-3 bg-green-100 rounded"><p className="text-sm text-green-700">Actual Savings: <strong>€{parseFloat(i.actual_savings).toLocaleString()}</strong></p></div>}
      <div className="grid grid-cols-2 gap-3 mb-3"><div className="flex items-center gap-2"><div className={`h-5 w-5 rounded-full flex items-center justify-center ${i.documentation_complete ? "bg-green-500" : "bg-gray-300"}`}><CheckCircle2 className="h-3 w-3 text-white" /></div><span className="text-sm">Documentation Complete</span></div><div className="flex items-center gap-2"><div className={`h-5 w-5 rounded-full flex items-center justify-center ${i.training_complete ? "bg-green-500" : "bg-gray-300"}`}><CheckCircle2 className="h-3 w-3 text-white" /></div><span className="text-sm">Training Complete</span></div></div>
      {i.lessons_learned && <div className="mb-2"><p className="text-xs font-semibold text-muted-foreground">Lessons Learned</p><p className="text-sm">{i.lessons_learned}</p></div>}
      {i.sustainability_plan && <div><p className="text-xs font-semibold text-muted-foreground">Sustainability Plan</p><p className="text-sm">{i.sustainability_plan}</p></div>}
    </CardContent></Card>))}</div>)}
  </div>
  <Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>{editing ? pt("Edit") : pt("Add")} Closure Report</DialogTitle></DialogHeader><div className="space-y-4"><div className="grid grid-cols-2 gap-4"><div className="space-y-2"><Label>{pt("Title")} *</Label><Input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></div><div className="space-y-2"><Label>Actual Savings (€)</Label><Input type="number" value={form.actual_savings} onChange={(e) => setForm({ ...form, actual_savings: e.target.value })} /></div></div><div className="space-y-2"><Label>Lessons Learned</Label><textarea className="w-full min-h-[60px] px-3 py-2 border rounded-md bg-background" value={form.lessons_learned} onChange={(e) => setForm({ ...form, lessons_learned: e.target.value })} /></div><div className="space-y-2"><Label>Sustainability Plan</Label><textarea className="w-full min-h-[60px] px-3 py-2 border rounded-md bg-background" value={form.sustainability_plan} onChange={(e) => setForm({ ...form, sustainability_plan: e.target.value })} /></div><div className="flex gap-6"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.documentation_complete} onChange={(e) => setForm({ ...form, documentation_complete: e.target.checked })} /> Documentation Complete</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.training_complete} onChange={(e) => setForm({ ...form, training_complete: e.target.checked })} /> Training Complete</label></div><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setDialogOpen(false)}>{pt("Cancel")}</Button><Button onClick={handleSave} disabled={submitting}>{submitting && <Loader2 className="h-4 w-4 animate-spin mr-2" />}{pt("Save")}</Button></div></div></DialogContent></Dialog></div>);
};
export default SixSigmaClosure;
