# Generated by Django 4.2.28 on 2026-02-05 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_budgetcategory_budgetitem_projectbudget'),
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('workflow', 'Workflow'), ('quality', 'Quality'), ('team', 'Team'), ('process', 'Process')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_policies', to='projects.project')),
            ],
            options={
                'db_table': 'kanban_work_policies',
                'ordering': ['order', 'id'],
            },
        ),
    ]
