# Generated by Django 4.2.28 on 2026-02-05 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_budgetcategory_budgetitem_projectbudget'),
        ('agile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinitionOfDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('development', 'Development'), ('testing', 'Testing'), ('review', 'Review'), ('documentation', 'Documentation'), ('quality', 'Quality'), ('acceptance', 'Acceptance'), ('security', 'Security')], max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agile_dod', to='projects.project')),
            ],
            options={
                'db_table': 'agile_definition_of_done',
                'ordering': ['order', 'id'],
            },
        ),
    ]
