# Generated by Django 4.2.28 on 2026-02-07 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_alter_customuser_role_alter_teaminvitation_role'),
        ('programs', '0002_programbudget_programbudgetcategory_and_more'),
        ('projects', '0008_budgetcategory_budgetitem_projectbudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('closed', 'Closed')], default='active', max_length=50)),
                ('strategic_objectives', models.TextField(blank=True, help_text='High-level strategic objectives')),
                ('budget_allocated', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='accounts.company')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GovernanceStakeholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('executive_sponsor', 'Executive Sponsor'), ('senior_responsible_owner', 'Senior Responsible Owner'), ('business_change_manager', 'Business Change Manager'), ('project_executive', 'Project Executive'), ('key_stakeholder', 'Key Stakeholder')], max_length=50)),
                ('influence_level', models.CharField(choices=[('high', 'High - Decision Maker'), ('medium', 'Medium - Influencer'), ('low', 'Low - Informed')], default='medium', max_length=20)),
                ('interest_level', models.CharField(choices=[('high', 'High Interest'), ('medium', 'Medium Interest'), ('low', 'Low Interest')], default='medium', max_length=20)),
                ('communication_plan', models.TextField(blank=True, help_text='How to engage this stakeholder')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='governance.portfolio')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='governance_stakeholders', to='programs.program')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='governance_stakeholders', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Governance Stakeholder',
                'verbose_name_plural': 'Governance Stakeholders',
            },
        ),
        migrations.CreateModel(
            name='GovernanceBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('board_type', models.CharField(choices=[('steering_committee', 'Steering Committee'), ('program_board', 'Program Board'), ('project_board', 'Project Board'), ('advisory_board', 'Advisory Board'), ('executive_board', 'Executive Board')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('meeting_frequency', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_boards', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='governance.portfolio')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='governance_boards', to='programs.program')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='governance_boards', to='projects.project')),
            ],
            options={
                'verbose_name': 'Governance Board',
                'verbose_name_plural': 'Governance Boards',
            },
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('chair', 'Chair'), ('member', 'Member'), ('secretary', 'Secretary'), ('observer', 'Observer')], default='member', max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='governance.governanceboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Board Member',
                'unique_together': {('board', 'user')},
            },
        ),
    ]
