# Generated by Django 4.2.28 on 2026-02-05 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_budgetcategory_budgetitem_projectbudget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prince2', '0002_remove_endstagereport_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('specialist', 'Specialist Product'), ('management', 'Management Product')], default='specialist', max_length=50)),
                ('format', models.CharField(blank=True, max_length=100)),
                ('quality_criteria', models.TextField(blank=True, help_text='Quality criteria for this product')),
                ('quality_tolerance', models.TextField(blank=True, help_text='Acceptable deviation from quality criteria')),
                ('quality_method', models.CharField(blank=True, help_text='How quality will be checked', max_length=200)),
                ('derivation', models.TextField(blank=True, help_text='Source/composition of the product')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('quality_check', 'Quality Check'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='planned', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prince2_owned_products', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prince2_products', to='projects.project')),
                ('quality_responsibility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prince2_quality_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
