# Generated by Django 5.2.6 on 2025-10-02 11:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0003_document_trainingmaterial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("Weekly", "Weekly"),
                            ("Bi-weekly", "Bi-weekly"),
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("One-time", "One-time"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Steering", "Steering"),
                            ("Program Board", "Program Board"),
                            ("Team", "Team"),
                            ("Milestone", "Milestone"),
                            ("Stage", "Stage"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("view", models.BooleanField(default=True)),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="reports/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reporting_items",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StatusReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                        ],
                        default="Not Started",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("last_updated", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_reports",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "status_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("End Users", "End Users"),
                            ("Administrators", "Administrators"),
                            ("Trainers", "Trainers"),
                        ],
                        default="End Users",
                        max_length=50,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("MP4", "MP4"), ("DOCX", "DOCX")],
                        default="PDF",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("Draft", "Draft"),
                            ("In Review", "In Review"),
                            ("Completed", "Completed"),
                        ],
                        default="Not Started",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_training_materials",
                        related_query_name="communication_training_material",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "training_materials",
                "ordering": ["-created_at"],
            },
        ),
    ]
