# Generated by Django 5.2.6 on 2026-02-01 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_budgetcategory_budgetitem_projectbudget'),
        ('scrum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definitionofdone',
            options={'ordering': ['order'], 'verbose_name_plural': 'Definitions of Done'},
        ),
        migrations.AlterModelOptions(
            name='sprintreview',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='definitionofdone',
            name='checklist',
            field=models.JSONField(blank=True, default=list, help_text="List of criteria: [{'item': 'Code reviewed', 'required': true}]"),
        ),
        migrations.AddField(
            model_name='definitionofdone',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='definitionofdone',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='definitionofdone',
            name='name',
            field=models.CharField(default='Definition of Done', max_length=200),
        ),
        migrations.AddField(
            model_name='definitionofdone',
            name='scope',
            field=models.CharField(blank=True, choices=[('project', 'Project Level'), ('sprint', 'Sprint Level'), ('task', 'Task Level')], default='project', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='definitionofdone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sprintreview',
            name='action_items',
            field=models.JSONField(blank=True, default=list, help_text='Action items from the review'),
        ),
        migrations.AddField(
            model_name='sprintreview',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='sprint_review_attended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sprintreview',
            name='completed_story_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sprintreview',
            name='demo_items',
            field=models.ManyToManyField(blank=True, related_name='sprint_reviews_demo', to='scrum.backlogitem'),
        ),
        migrations.AddField(
            model_name='sprintreview',
            name='duration_minutes',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
        migrations.AddField(
            model_name='sprintreview',
            name='facilitator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint_review_facilitated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sprintreview',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sprintreview',
            name='sprint_goal_achieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sprintreview',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, related_name='sprint_review_stakeholders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sprintreview',
            name='status',
            field=models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='backlogitem',
            name='title',
            field=models.CharField(default='New Item', max_length=300),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='name',
            field=models.CharField(default='New Sprint', max_length=100),
        ),
        migrations.CreateModel(
            name='SprintGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='What do we want to achieve this sprint?')),
                ('success_criteria', models.JSONField(blank=True, default=list, help_text='List of criteria to measure success')),
                ('is_achieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint_goals_created', to=settings.AUTH_USER_MODEL)),
                ('sprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_goal', to='scrum.sprint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SprintPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=120, help_text='Meeting duration in minutes')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('team_capacity', models.IntegerField(blank=True, help_text='Total story points team can commit to', null=True)),
                ('committed_story_points', models.IntegerField(default=0, help_text='Story points committed during planning')),
                ('notes', models.TextField(blank=True)),
                ('decisions', models.JSONField(blank=True, default=list, help_text='Key decisions made during planning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='sprint_planning_attended', to=settings.AUTH_USER_MODEL)),
                ('facilitator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint_planning_facilitated', to=settings.AUTH_USER_MODEL)),
                ('sprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planning_meeting', to='scrum.sprint')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='DoDChecklistCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('task', 'Task'), ('sprint', 'Sprint'), ('increment', 'Increment')], max_length=20)),
                ('item_id', models.IntegerField(help_text='ID of the task/sprint/increment')),
                ('completed_items', models.JSONField(default=list, help_text='List of completed checklist item indices')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_fully_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('definition_of_done', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='scrum.definitionofdone')),
            ],
            options={
                'unique_together': {('definition_of_done', 'item_type', 'item_id')},
            },
        ),
        migrations.CreateModel(
            name='Increment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Version number (e.g., 1.0.0, Sprint-5)', max_length=50)),
                ('description', models.TextField(help_text="What's included in this increment")),
                ('is_released', models.BooleanField(default=False, help_text='Has this increment been released to production?')),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('release_notes', models.TextField(blank=True)),
                ('meets_dod', models.BooleanField(default=False, help_text='Does this increment meet Definition of Done?')),
                ('test_coverage', models.DecimalField(blank=True, decimal_places=2, help_text='Test coverage percentage', max_digits=5, null=True)),
                ('artifacts', models.JSONField(blank=True, default=list, help_text='Links to builds, deployments, documentation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_tasks', models.ManyToManyField(blank=True, related_name='increments', to='scrum.backlogitem')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increments', to='projects.project')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increments', to='scrum.sprint')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'version')},
            },
        ),
    ]
