# Generated by Django 5.2.6 on 2025-10-01 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_plans_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_plan', to='projects.project')),
            ],
            options={
                'verbose_name': 'Deployment Plan',
                'verbose_name_plural': 'Deployment Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RolloutPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deployment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollout_phases', to='deploment.deploymentplan')),
            ],
            options={
                'verbose_name': 'Rollout Phase',
                'verbose_name_plural': 'Rollout Phases',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rollout_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='deploment.rolloutphase')),
            ],
            options={
                'verbose_name': 'Phase Task',
                'verbose_name_plural': 'Phase Tasks',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deployment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_items', to='deploment.deploymentplan')),
            ],
            options={
                'verbose_name': 'Strategy Item',
                'verbose_name_plural': 'Strategy Items',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
