# Generated by Django 5.2.6 on 2025-10-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deploymentplan",
            name="rollout_overview",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="deploymentplan",
            name="strategy_overview",
            field=models.TextField(blank=True, default=""),
        ),
    ]
