import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'nl';

const translations = {
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      features: 'Features',
      pricing: 'Pricing',
      contact: 'Contact',
      login: 'Log In',
      logout: 'Logout',
      openApp: 'Open App',
      website: 'Website',
      dashboard: 'Dashboard',
      projects: 'Projects',
      programs: 'Programs',
      team: 'Team',
      settings: 'Settings',
      academy: {
        title: 'Academy',
        comingSoon: 'Coming Soon',
        new: 'New',
        marketplace: 'Training Marketplace',
        marketplaceDesc: '100+ courses & certificates',
        methodologies: 'Management Methodologies',
        methodologiesDesc: 'Scrum, Kanban, PRINCE2, SAFe & more',
        pricing: 'Academy Pricing',
        pricingDesc: 'Subscriptions & certifications',
        requestQuote: 'Request Quote',
        requestQuoteDesc: 'For teams & companies',
      }
    },
    hero: {
      badge: 'Next-Gen Project Management',
      title1: 'Master Your Projects',
      title2: 'with AI-Powered Intelligence',
      subtitle: 'The all-in-one platform for program & project management. Powered by AI, built for teams that want to achieve more.',
      programManagement: 'Program Management',
      projectTracking: 'Project Tracking',
      aiInsights: 'AI Insights',
      timeManagement: 'Time Management',
      getStarted: 'Get Started Free',
      watchDemo: 'Watch Demo',
      aiGreeting: "Hi! I'm your AI project assistant. I can help you with:",
      aiCapabilities: [
        'Creating project plans & timelines',
        'Risk analysis & mitigation',
        'Status reports & dashboards',
        'Team capacity planning',
      ],
      askPlaceholder: 'Ask me anything about your projects...',
      stats: {
        projects: 'Projects Managed',
        programs: 'Active Programs',
        hours: 'Hours Tracked',
        success: 'Success Rate',
      },
      aiPowered: 'AI-Powered',
      sales: 'Sales',
      online: 'Online',
      welcome: '👋 Welcome to ProjeXtPal! I\'m happy to help with:',
      capabilities: [
        'Explanation of our AI features',
        'Pricing and subscriptions',
        'Scheduling a demo',
        'Technical questions'
      ],
      poweredBy: 'Powered by AI • Average response: 2 sec',
      quickPrompts: [
        'What can ProjeXtPal do for me?',
        'How does AI improve my projects?',
        'Is there a free trial?',
        'What does ProjeXtPal cost?'
      ],
      chatPlaceholder: '💬 Ask your question about ProjeXtPal...',
      safePrivate: 'Safe & private',
      instantResponse: 'Instant response',
    },
    about: {
      badge: 'Why ProjeXtPal',
      title1: 'Everything You Need',
      title2: 'In One Platform',
      description: "ProjeXtPal combines powerful project management with intelligent AI assistance. Whether you're managing a single project or an entire portfolio, we've got you covered.",
      capabilities: [
        'Multi-methodology support (Agile, Scrum, PRINCE2, SAFe)',
        'Real-time collaboration & communication',
        'Automated reporting & insights',
        'Integrated time tracking',
        'AI-powered recommendations',
      ],
      getStarted: 'Get Started',
      programs: 'Programs',
      programsDesc: 'Manage portfolios and complex programs with ease.',
      projects: 'Projects',
      projectsDesc: 'Track tasks, timelines, and deliverables efficiently.',
      aiPowered: 'AI-Powered',
      aiPoweredDesc: 'Get intelligent insights and recommendations powered by advanced AI.',
      smartEntry: 'Smart Data Entry',
      aiReports: 'AI Reports',
      methodologyAdvisor: 'Methodology Advisor',
      pillars: [
        { title: 'Projects', desc: 'AI-powered project management' },
        { title: 'Programs', desc: 'Portfolio & programs' },
        { title: 'Trainings', desc: '118+ learning modules' },
        { title: 'AI', desc: 'Intelligent assistance' }
      ]
    },
    features: {
      badge: 'Powerful Features',
      title1: 'Tools That',
      title2: 'Empower Your Team',
      items: [
        { title: 'Program Management', desc: 'Oversee multiple projects with portfolio dashboards and strategic alignment.' },
        { title: 'Project Tracking', desc: 'Gantt charts, Kanban boards, and milestone tracking all in one place.' },
        { title: 'AI Assistant', desc: 'Get instant answers, generate reports, and receive smart recommendations.' },
        { title: 'Time Tracking', desc: 'Log hours, track productivity, and manage team capacity effortlessly.' },
        { title: 'Team Collaboration', desc: 'Real-time updates, comments, and notifications keep everyone aligned.' },
        { title: 'Smart Automation', desc: 'Automate repetitive tasks and focus on what matters most.' },
        { title: 'Analytics & Reports', desc: 'Beautiful dashboards and exportable reports at your fingertips.' },
        { title: 'Risk Management', desc: 'Identify, assess, and mitigate risks before they become issues.' },
        { title: 'Resource Planning', desc: 'Optimize team allocation and prevent burnout with smart planning.' },
      ],
      startUsing: 'Start Using ProjeXtPal',
    },
    demo: {
      badge: 'See It In Action',
      title1: 'Experience',
      title2: 'The Power of ProjeXtPal',
      aiOnline: 'AI Online',
      aiInsight: 'AI Insight',
      aiInsightText: 'Project "Digital Transformation" is 15% ahead of schedule. Consider reallocating resources to the delayed "CRM Integration" project.',
      tryIt: 'Try It Yourself',
    },
    app: {
      totalPrograms: 'Total Programs',
      totalProjects: 'Total Projects',
      dashboardTitle: 'Portfolio Dashboard',
      dashboardSubtitle: 'Your complete project & program overview',
      aiSummary: 'AI Summary',
      programsStatus: 'Programs Status',
      projectsStatus: 'Projects Status',
      active: 'Active',
      inProgress: 'In Progress',
      atRisk: 'At Risk',
      budget: 'Budget',
      totalBudget: 'Total Budget',
      avgProgress: 'Avg Progress',
      newProgram: 'New Program',
      newProject: 'New Project',
      viewAll: 'View All',
      name: 'Name',
      methodology: 'Methodology',
      progress: 'Progress',
      status: 'Status',
      health: 'Health',
      dueDate: 'Due Date',
      planning: 'Planning',
      pending: 'Pending',
      quickActions: 'Quick Actions',
      aiAssistant: 'AI Assistant',
      programsOverview: 'Programs Overview',
      projectsOverview: 'Projects Overview',
      completed: 'Completed',
      framework: 'Framework',
      programName: 'Program Name',
      projects: 'Projects',
      requiresAttention: 'Requires Attention',
      total: 'Total',
      totalAllocated: 'Total Allocated',
      activePrograms: 'Active Programs',
      activeProjects: 'Active Projects',
      onHold: 'On Hold',
    },
    timeTracking: {
      title: 'Time Tracking',
      subtitle: 'Track your time across projects and tasks',
      aiInsights: 'AI Insights',
      smartEntry: 'Smart Entry',
      aiReport: 'AI Report',
      newTimeEntry: 'New Time Entry',
      today: 'Today',
      thisWeek: 'This Week',
      activeTimer: 'Active Timer',
      project: 'Project',
      task: 'Task',
      startTimer: 'Start Timer',
      stopSave: 'Stop & Save',
      timeReports: 'Time Reports',
      weekly: 'Weekly',
      monthly: 'Monthly',
      dailyHours: 'Daily Hours',
      weeklyHours: 'Weekly Hours',
      projectDistribution: 'Project Distribution',
      totalHours: 'Total Hours',
      totalEntries: 'Total Entries',
      projects: 'Projects',
      dailyAverage: 'Daily Average',
      recentEntries: 'Recent Time Entries',
      filters: 'Filters',
      clearFilters: 'Clear Filters',
      allProjects: 'All projects',
      allMembers: 'All members',
      teamMember: 'Team Member',
      startDate: 'Start Date',
      endDate: 'End Date',
      showing: 'Showing',
      of: 'of',
      entries: 'entries',
      noEntries: 'No time entries match the current filters',
      clearAllFilters: 'Clear all filters',
      logTimeEntry: 'Log Time Entry',
      selectProject: 'Select project',
      selectTask: 'Select task',
      date: 'Date',
      hours: 'Hours',
      minutes: 'Minutes',
      description: 'Description (optional)',
      saveTimeEntry: 'Save Time Entry',
      aiProductivityInsights: 'AI Productivity Insights',
      aiInsightsDesc: 'AI-powered analysis of your time tracking patterns.',
      analyzeMyTime: 'Analyze My Time',
      analyzingPatterns: 'Analyzing your productivity patterns...',
      refreshAnalysis: 'Refresh Analysis',
      close: 'Close',
      aiSmartEntry: 'AI Smart Time Entry',
      aiSmartEntryDesc: 'Describe your work and AI will create the time entry.',
      generateEntry: 'Generate Entry',
      processing: 'Processing...',
      addEntry: 'Add Entry',
      tryAgain: 'Try Again',
      aiSuggestion: 'AI Suggestion',
      duration: 'Duration',
      aiWeeklyReport: 'AI Weekly Report',
      aiReportDesc: 'Generate a professional time report summary.',
      generateReport: 'Generate Report',
      generatingReport: 'Generating your report...',
      copyReport: 'Copy Report',
      regenerate: 'Regenerate',
    },
    programs: {
      title: 'Programs',
      subtitle: 'Manage your program portfolio',
      totalPrograms: 'Total Programs',
      totalProjects: 'Total Projects',
      newProgram: 'New Program',
      createProgram: 'Create Program',
      createNewProgram: 'Create New Program',
      editProgram: 'Edit Program',
      deleteProgram: 'Delete Program',
      programDetails: 'Program Details',
      programName: 'Program Name',
      programNameRequired: 'Program name is required',
      description: 'Description',
      strategicObjective: 'Strategic Objective',
      departments: 'Departments',
      departmentsPlaceholder: 'Enter departments',
      budget: 'Budget',
      budgetPlaceholder: 'Enter budget',
      totalBudget: 'Total Budget',
      spent: 'Spent',
      duration: 'Duration',
      durationPlaceholder: 'Duration in months',
      months: 'months',
      startDate: 'Start Date',
      planning: 'Planning',
      active: 'Active',
      completed: 'Completed',
      atRisk: 'At Risk',
      health: 'Health',
      projects: 'Projects',
      unassigned: 'Unassigned',
      allStatus: 'All Status',
      allMethods: 'All Methodologies',
      searchPlaceholder: 'Search programs...',
      noPrograms: 'No programs found',
      view: 'View',
      edit: 'Edit',
      delete: 'Delete',
      cancel: 'Cancel',
      saveChanges: 'Save Changes',
      saving: 'Saving...',
      updateDetails: 'Update Details',
      deleteConfirm: 'Are you sure you want to delete this program?',
      createDescription: 'Create a new program to manage multiple related projects',
      manual: 'Manual Entry',
      aiAssistant: 'AI Assistant',
      aiAssistantDesc: 'Let AI help you set up your program',
      describeProgram: 'Describe Your Program',
      describeProgramHint: 'Tell us about your program goals and scope',
      ideaPlaceholder: 'E.g., Digital transformation initiative for modernizing our customer service platforms...',
      ideaTip: 'The more details you provide, the better AI can help',
      analyzeRecommend: 'Analyze & Recommend',
      analyzing: 'Analyzing your program...',
      recommendedMethodology: 'Recommended Methodology',
      match: 'Match',
      orChooseAnother: 'Or choose another methodology',
      recommendationHint: 'Based on your program description',
      reviewProgram: 'Review Program Details',
      reviewDetails: 'Review the generated details and make adjustments',
      reviewHint: 'You can edit any field before creating',
      back: 'Back',
      creatingProgram: 'Creating program...',
      settingUp: 'Setting up your program...',
      generateWithAI: 'Generate with AI',
      review: 'Review',
      methodologies: {
        safe: 'SAFe',
        safeDesc: 'Scaled Agile Framework for enterprise-wide agile transformation',
        msp: 'MSP',
        mspDesc: 'Managing Successful Programmes - governance-focused approach',
        pmi: 'PMI Program Management',
        pmiDesc: 'PMI standard for program management with benefits realization focus',
        prince2: 'PRINCE2 Programme',
        prince2Desc: 'PRINCE2 methodology adapted for programme management',
        hybrid: 'Hybrid',
        hybridDesc: 'Flexible combination of methodologies',
      },
    },
    pricing: {
      badge: 'Simple Pricing',
      title1: 'Choose The Plan',
      title2: 'That Fits Your Needs',
      popular: 'Most Popular',
      monthly: '/month',
      getStarted: 'Get Started',
      contactUs: 'Contact Us',
      plans: [
        {
          name: 'Basic',
          desc: 'Perfect for small teams getting started.',
          price: '€25',
          features: ['Up to 5 users', 'Up to 10 projects', '5 GB storage', 'Basic AI assistance', 'Email support'],
          academy: 'optional',
        },
        {
          name: 'Professional',
          desc: 'For growing teams that need more power.',
          price: '€75',
          features: ['Up to 25 users', 'Up to 50 projects', '25 GB storage', 'Advanced AI features', 'Priority support', 'Custom reports'],
          academy: 'optional',
        },
        {
          name: 'Enterprise',
          desc: 'For large organizations with complex needs.',
          price: '€200',
          features: ['Unlimited users', 'Unlimited projects', 'Unlimited storage', 'SSO & advanced security', 'Dedicated manager', 'Custom integrations', '✓ Learning Academy included'],
          academy: 'included',
        },
        {
          name: 'Custom+',
          desc: 'Tailored solution for your organization.',
          price: 'Quote',
          features: ['Everything in Enterprise', 'On-premise deployment', 'Custom SLA', 'Dedicated infrastructure', 'White-label options', '24/7 support'],
          academy: 'optional',
        },
      ],
    },
    contact: {
      badge: 'Get In Touch',
      title: "Let's Talk",
      letsTalk: "We'd Love To Hear From You",
      description: 'Questions about ProjeXtPal? Want to schedule a demo? Our team is here to help.',
      name: 'Your Name',
      email: 'Your Email',
      message: 'Your Message',
      send: 'Send Message',
    },
    faq: {
      title: 'Frequently Asked Questions',
      items: [
        { q: 'What methodologies does ProjeXtPal support?', a: 'ProjeXtPal supports Agile, Scrum, Kanban, PRINCE2, SAFe, Lean Six Sigma, and traditional Waterfall methodologies.' },
        { q: 'Is there a free trial?', a: 'Yes! Our Basic plan includes core features to get you started. No credit card required.' },
        { q: 'Can I import data from other tools?', a: 'Absolutely. We support imports from Jira, Asana, Monday, Trello, MS Project, and Excel.' },
        { q: 'How does the AI assistant work?', a: 'Our AI is trained on project management best practices and your project data to provide contextual recommendations and automate routine tasks.' },
      ],
    },
    footer: {
      description: 'AI-powered project management for modern teams.',
      product: 'Product',
      company: 'Company',
      legal: 'Legal',
      rights: 'All rights reserved.',
      cta: {
        title1: 'Ready to Transform',
        title2: 'Your Project Management?',
      },
      demo: 'Demo',
      privacy: 'Privacy',
      terms: 'Terms',
      academy: {
        courses: 'Courses',
        methodologies: 'Methodologies',
        pricing: 'Pricing',
      }
    },
    common: {
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      add: 'Add',
      search: 'Search',
      loading: 'Loading...',
      confirm: 'Confirm',
      back: 'Back',
      next: 'Next',
      close: 'Close',
      success: 'Success',
      error: 'Error',
      retry: 'Retry',
    },
  },
  nl: {
    nav: {
      home: 'Home',
      about: 'Over Ons',
      features: 'Functies',
      pricing: 'Prijzen',
      contact: 'Contact',
      login: 'Inloggen',
      logout: 'Uitloggen',
      openApp: 'Open App',
      website: 'Website',
      dashboard: 'Dashboard',
      projects: 'Projecten',
      programs: "Programma's",
      team: 'Team',
      settings: 'Instellingen',
      academy: {
        title: 'Academy',
        comingSoon: 'Binnenkort',
        new: 'Nieuw',
        marketplace: 'Training Marketplace',
        marketplaceDesc: '100+ cursussen & certificaten',
        methodologies: 'Management Methodieken',
        methodologiesDesc: 'Scrum, Kanban, PRINCE2, SAFe & meer',
        pricing: 'Academy Prijzen',
        pricingDesc: 'Abonnementen & certificeringen',
        requestQuote: 'Offerte Aanvragen',
        requestQuoteDesc: 'Voor teams & bedrijven',
      }
    },
    hero: {
      badge: 'Next-Gen Projectmanagement',
      title1: 'Beheers Je Projecten',
      title2: 'met AI-Powered Intelligentie',
      subtitle: 'Het alles-in-één platform voor programma- en projectmanagement. Aangedreven door AI, gebouwd voor teams die meer willen bereiken.',
      programManagement: 'Programmamanagement',
      projectTracking: 'Projecttracking',
      aiInsights: 'AI Inzichten',
      timeManagement: 'Tijdregistratie',
      getStarted: 'Gratis Starten',
      watchDemo: 'Bekijk Demo',
      aiGreeting: 'Hoi! Ik ben je AI projectassistent. Ik kan je helpen met:',
      aiCapabilities: [
        'Projectplannen & tijdlijnen maken',
        'Risicoanalyse & mitigatie',
        'Statusrapporten & dashboards',
        'Team capaciteitsplanning',
      ],
      askPlaceholder: 'Vraag me alles over je projecten...',
      stats: {
        projects: 'Projecten Beheerd',
        programs: "Actieve Programma's",
        hours: 'Uren Geregistreerd',
        success: 'Succesratio',
      },
      aiPowered: 'AI-Powered',
      sales: 'Sales',
      online: 'Online',
      welcome: '👋 Welkom bij ProjeXtPal! Ik help je graag met:',
      capabilities: [
        'Uitleg over onze AI-functies',
        'Prijzen en abonnementen',
        'Een demo inplannen',
        'Technische vragen'
      ],
      poweredBy: 'Powered by AI • Gemiddelde responstijd: 2 sec',
      quickPrompts: [
        'Wat kan ProjeXtPal voor mij doen?',
        'Hoe verbetert AI mijn projecten?',
        'Is er een gratis proefversie?',
        'Wat kost ProjeXtPal?'
      ],
      chatPlaceholder: '💬 Stel je vraag over ProjeXtPal...',
      safePrivate: 'Veilig & privé',
      instantResponse: 'Direct antwoord',
    },
    about: {
      badge: 'Waarom ProjeXtPal',
      title1: 'Alles Wat Je Nodig Hebt',
      title2: 'In Één Platform',
      description: 'ProjeXtPal combineert krachtig projectmanagement met intelligente AI-assistentie. Of je nu één project beheert of een complete portfolio, wij hebben je gedekt.',
      capabilities: [
        'Multi-methodologie ondersteuning (Agile, Scrum, PRINCE2, SAFe)',
        'Real-time samenwerking & communicatie',
        'Geautomatiseerde rapportage & inzichten',
        'Geïntegreerde tijdregistratie',
        'AI-powered aanbevelingen',
      ],
      getStarted: 'Aan de Slag',
      programs: "Programma's",
      programsDesc: "Beheer portfolio's en complexe programma's met gemak.",
      projects: 'Projecten',
      projectsDesc: 'Volg taken, tijdlijnen en deliverables efficiënt.',
      aiPowered: 'AI-Powered',
      aiPoweredDesc: 'Krijg intelligente inzichten en aanbevelingen aangedreven door geavanceerde AI.',
      smartEntry: 'Slimme Data Invoer',
      aiReports: 'AI Rapporten',
      methodologyAdvisor: 'Methodologie Adviseur',
      pillars: [
        { title: 'Projecten', desc: 'Projectmanagement met AI' },
        { title: "Programma's", desc: "Portfolio & programma's" },
        { title: 'Trainingen', desc: '118+ leermodules' },
        { title: 'AI', desc: 'Intelligente assistentie' }
      ]
    },
    features: {
      badge: 'Krachtige Functies',
      title1: 'Tools Die',
      title2: 'Je Team Versterken',
      items: [
        { title: 'Programmamanagement', desc: 'Overzicht over meerdere projecten met portfolio dashboards en strategische afstemming.' },
        { title: 'Projecttracking', desc: 'Gantt charts, Kanban borden en milestone tracking allemaal op één plek.' },
        { title: 'AI Assistent', desc: 'Krijg directe antwoorden, genereer rapporten en ontvang slimme aanbevelingen.' },
        { title: 'Tijdregistratie', desc: 'Log uren, volg productiviteit en beheer teamcapaciteit moeiteloos.' },
        { title: 'Team Samenwerking', desc: 'Real-time updates, comments en notificaties houden iedereen op de hoogte.' },
        { title: 'Slimme Automatisering', desc: 'Automatiseer repetitieve taken en focus op wat er echt toe doet.' },
        { title: 'Analytics & Rapporten', desc: 'Mooie dashboards en exporteerbare rapporten binnen handbereik.' },
        { title: 'Risicomanagement', desc: "Identificeer, beoordeel en mitigeer risico's voordat ze problemen worden." },
        { title: 'Resource Planning', desc: 'Optimaliseer teamallocatie en voorkom burnout met slimme planning.' },
      ],
      startUsing: 'Start Met ProjeXtPal',
    },
    demo: {
      badge: 'Zie Het In Actie',
      title1: 'Ervaar',
      title2: 'De Kracht van ProjeXtPal',
      aiOnline: 'AI Online',
      aiInsight: 'AI Inzicht',
      aiInsightText: 'Project "Digitale Transformatie" loopt 15% voor op schema. Overweeg resources te verplaatsen naar het vertraagde "CRM Integratie" project.',
      tryIt: 'Probeer Het Zelf',
    },
    app: {
      totalPrograms: "Totaal Programma's",
      totalProjects: 'Totaal Projecten',
      dashboardTitle: 'Portfolio Dashboard',
      dashboardSubtitle: 'Je complete project & programma overzicht',
      aiSummary: 'AI Samenvatting',
      programsStatus: 'Programma Status',
      projectsStatus: 'Project Status',
      active: 'Actief',
      inProgress: 'In Uitvoering',
      atRisk: 'Risico',
      budget: 'Budget',
      totalBudget: 'Totaal Budget',
      avgProgress: 'Gem. Voortgang',
      newProgram: 'Nieuw Programma',
      newProject: 'Nieuw Project',
      viewAll: 'Bekijk Alle',
      name: 'Naam',
      methodology: 'Methodologie',
      progress: 'Voortgang',
      status: 'Status',
      health: 'Gezondheid',
      dueDate: 'Deadline',
      planning: 'Planning',
      pending: 'In Afwachting',
      quickActions: 'Snelle Acties',
      aiAssistant: 'AI Assistent',
      programsOverview: 'Programma Overzicht',
      projectsOverview: 'Project Overzicht',
      completed: 'Voltooid',
      framework: 'Framework',
      programName: 'Programma Naam',
      projects: 'Projecten',
      requiresAttention: 'Vereist Aandacht',
      total: 'Totaal',
      totalAllocated: 'Totaal Toegewezen',
      activePrograms: 'Actieve Programma\'s',
      activeProjects: 'Actieve Projecten',
      onHold: 'In de Wacht',
    },
    timeTracking: {
      title: 'Tijdregistratie',
      subtitle: 'Registreer je tijd per project en taak',
      aiInsights: 'AI Inzichten',
      smartEntry: 'Slimme Invoer',
      aiReport: 'AI Rapport',
      newTimeEntry: 'Nieuwe Tijdregistratie',
      today: 'Vandaag',
      thisWeek: 'Deze Week',
      activeTimer: 'Actieve Timer',
      project: 'Project',
      task: 'Taak',
      startTimer: 'Start Timer',
      stopSave: 'Stop & Opslaan',
      timeReports: 'Tijdrapporten',
      weekly: 'Wekelijks',
      monthly: 'Maandelijks',
      dailyHours: 'Dagelijkse Uren',
      weeklyHours: 'Wekelijkse Uren',
      projectDistribution: 'Project Verdeling',
      totalHours: 'Totaal Uren',
      totalEntries: 'Totaal Registraties',
      projects: 'Projecten',
      dailyAverage: 'Dagelijks Gemiddelde',
      recentEntries: 'Recente Tijdregistraties',
      filters: 'Filters',
      clearFilters: 'Wis Filters',
      allProjects: 'Alle projecten',
      allMembers: 'Alle leden',
      teamMember: 'Teamlid',
      startDate: 'Startdatum',
      endDate: 'Einddatum',
      showing: 'Tonen',
      of: 'van',
      entries: 'registraties',
      noEntries: 'Geen tijdregistraties gevonden',
      clearAllFilters: 'Wis alle filters',
      logTimeEntry: 'Tijd Registreren',
      selectProject: 'Selecteer project',
      selectTask: 'Selecteer taak',
      date: 'Datum',
      hours: 'Uren',
      minutes: 'Minuten',
      description: 'Omschrijving (optioneel)',
      saveTimeEntry: 'Registratie Opslaan',
      aiProductivityInsights: 'AI Productiviteit Inzichten',
      aiInsightsDesc: 'AI-analyse van je tijdregistratie patronen.',
      analyzeMyTime: 'Analyseer Mijn Tijd',
      analyzingPatterns: 'Je productiviteitspatronen analyseren...',
      refreshAnalysis: 'Ververs Analyse',
      close: 'Sluiten',
      aiSmartEntry: 'AI Slimme Tijdregistratie',
      aiSmartEntryDesc: 'Beschrijf je werk en AI maakt de registratie.',
      generateEntry: 'Genereer Registratie',
      processing: 'Verwerken...',
      addEntry: 'Voeg Toe',
      tryAgain: 'Probeer Opnieuw',
      aiSuggestion: 'AI Suggestie',
      duration: 'Duur',
      aiWeeklyReport: 'AI Weekrapport',
      aiReportDesc: 'Genereer een professioneel tijdrapport.',
      generateReport: 'Genereer Rapport',
      generatingReport: 'Je rapport genereren...',
      copyReport: 'Kopieer Rapport',
      regenerate: 'Regenereer',
    },
    programs: {
      title: 'Programma\'s',
      subtitle: 'Beheer je programma portfolio',
      totalPrograms: 'Totaal Programma\'s',
      totalProjects: 'Totaal Projecten',
      newProgram: 'Nieuw Programma',
      createProgram: 'Programma Maken',
      createNewProgram: 'Nieuw Programma Maken',
      editProgram: 'Programma Bewerken',
      deleteProgram: 'Programma Verwijderen',
      programDetails: 'Programma Details',
      programName: 'Programma Naam',
      programNameRequired: 'Programma naam is verplicht',
      description: 'Omschrijving',
      strategicObjective: 'Strategisch Doel',
      departments: 'Afdelingen',
      departmentsPlaceholder: 'Voer afdelingen in',
      budget: 'Budget',
      budgetPlaceholder: 'Voer budget in',
      totalBudget: 'Totaal Budget',
      spent: 'Uitgegeven',
      duration: 'Duur',
      durationPlaceholder: 'Duur in maanden',
      months: 'maanden',
      startDate: 'Startdatum',
      planning: 'Planning',
      active: 'Actief',
      completed: 'Voltooid',
      atRisk: 'Risico',
      health: 'Gezondheid',
      projects: 'Projecten',
      unassigned: 'Niet toegewezen',
      allStatus: 'Alle Status',
      allMethods: 'Alle Methodologieën',
      searchPlaceholder: 'Zoek programma\'s...',
      noPrograms: 'Geen programma\'s gevonden',
      view: 'Bekijken',
      edit: 'Bewerken',
      delete: 'Verwijderen',
      cancel: 'Annuleren',
      saveChanges: 'Wijzigingen Opslaan',
      saving: 'Opslaan...',
      updateDetails: 'Details Bijwerken',
      deleteConfirm: 'Weet je zeker dat je dit programma wilt verwijderen?',
      createDescription: 'Maak een nieuw programma om meerdere gerelateerde projecten te beheren',
      manual: 'Handmatige Invoer',
      aiAssistant: 'AI Assistent',
      aiAssistantDesc: 'Laat AI je helpen bij het opzetten van je programma',
      describeProgram: 'Beschrijf Je Programma',
      describeProgramHint: 'Vertel ons over je programma doelen en scope',
      ideaPlaceholder: 'Bijv., Digitale transformatie initiatief voor modernisering van onze klantenservice platforms...',
      ideaTip: 'Hoe meer details je geeft, hoe beter AI kan helpen',
      analyzeRecommend: 'Analyseren & Aanbevelen',
      analyzing: 'Je programma analyseren...',
      recommendedMethodology: 'Aanbevolen Methodologie',
      match: 'Match',
      orChooseAnother: 'Of kies een andere methodologie',
      recommendationHint: 'Gebaseerd op je programma beschrijving',
      reviewProgram: 'Programma Details Bekijken',
      reviewDetails: 'Bekijk de gegenereerde details en maak aanpassingen',
      reviewHint: 'Je kunt elk veld bewerken voordat je aanmaakt',
      back: 'Terug',
      creatingProgram: 'Programma aanmaken...',
      settingUp: 'Je programma opzetten...',
      generateWithAI: 'Genereren met AI',
      review: 'Beoordelen',
      methodologies: {
        safe: 'SAFe',
        safeDesc: 'Scaled Agile Framework voor bedrijfsbrede agile transformatie',
        msp: 'MSP',
        mspDesc: 'Managing Successful Programmes - governance-gerichte aanpak',
        pmi: 'PMI Program Management',
        pmiDesc: 'PMI standaard voor programma management met voordelen realisatie focus',
        prince2: 'PRINCE2 Programme',
        prince2Desc: 'PRINCE2 methodologie aangepast voor programma management',
        hybrid: 'Hybride',
        hybridDesc: 'Flexibele combinatie van methodologieën',
      },
    },
    pricing: {
      badge: 'Eenvoudige Prijzen',
      title1: 'Kies Het Plan',
      title2: 'Dat Bij Je Past',
      popular: 'Meest Populair',
      monthly: '/maand',
      getStarted: 'Aan de Slag',
      contactUs: 'Neem Contact Op',
      plans: [
        {
          name: 'Basic',
          desc: 'Perfect voor kleine teams die beginnen.',
          price: '€25',
          features: ['Tot 5 gebruikers', 'Tot 10 projecten', '5 GB opslag', 'Basis AI assistentie', 'Email support'],
          academy: 'optional',
        },
        {
          name: 'Professional',
          desc: 'Voor groeiende teams die meer power nodig hebben.',
          price: '€75',
          features: ['Tot 25 gebruikers', 'Tot 50 projecten', '25 GB opslag', 'Geavanceerde AI functies', 'Prioriteit support', 'Custom rapporten'],
          academy: 'optional',
        },
        {
          name: 'Enterprise',
          desc: 'Voor grote organisaties met complexe behoeften.',
          price: '€200',
          features: ['Onbeperkt gebruikers', 'Onbeperkt projecten', 'Onbeperkt opslag', 'SSO & geavanceerde beveiliging', 'Dedicated manager', 'Custom integraties', '✓ Learning Academy inbegrepen'],
          academy: 'included',
        },
        {
          name: 'Custom+',
          desc: 'Oplossing op maat voor uw organisatie.',
          price: 'Offerte',
          features: ['Alles in Enterprise', 'On-premise deployment', 'Custom SLA', 'Dedicated infrastructuur', 'White-label opties', '24/7 support'],
          academy: 'optional',
        },
      ],
    },
    contact: {
      badge: 'Neem Contact Op',
      title: 'Laten We Praten',
      letsTalk: 'We Horen Graag Van Je',
      description: 'Vragen over ProjeXtPal? Wil je een demo inplannen? Ons team staat voor je klaar.',
      name: 'Je Naam',
      email: 'Je Email',
      message: 'Je Bericht',
      send: 'Verstuur Bericht',
    },
    faq: {
      title: 'Veelgestelde Vragen',
      items: [
        { q: 'Welke methodologieën ondersteunt ProjeXtPal?', a: 'ProjeXtPal ondersteunt Agile, Scrum, Kanban, PRINCE2, SAFe, Lean Six Sigma en traditionele Waterfall methodologieën.' },
        { q: 'Is er een gratis proefperiode?', a: 'Ja! Ons Basic plan bevat kernfuncties om te starten. Geen creditcard nodig.' },
        { q: 'Kan ik data importeren uit andere tools?', a: 'Absoluut. We ondersteunen imports vanuit Jira, Asana, Monday, Trello, MS Project en Excel.' },
        { q: 'Hoe werkt de AI assistent?', a: 'Onze AI is getraind op projectmanagement best practices en je projectdata om contextuele aanbevelingen te geven en routinetaken te automatiseren.' },
      ],
    },
    footer: {
      description: 'AI-powered projectmanagement voor moderne teams.',
      product: 'Product',
      company: 'Bedrijf',
      legal: 'Juridisch',
      rights: 'Alle rechten voorbehouden.',
      cta: {
        title1: 'Klaar Om Je',
        title2: 'Projectmanagement Te Transformeren?',
      },
      demo: 'Demo',
      privacy: 'Privacy',
      terms: 'Voorwaarden',
      academy: {
        courses: 'Cursussen',
        methodologies: 'Methodieken',
        pricing: 'Prijzen',
      }
    },
    common: {
      save: 'Opslaan',
      cancel: 'Annuleren',
      delete: 'Verwijderen',
      edit: 'Bewerken',
      add: 'Toevoegen',
      search: 'Zoeken',
      loading: 'Laden...',
      confirm: 'Bevestigen',
      back: 'Terug',
      next: 'Volgende',
      close: 'Sluiten',
      success: 'Succes',
      error: 'Fout',
      retry: 'Opnieuw',
    },
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: typeof translations.en;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('nl');
  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

export const languages = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'nl', name: 'Nederlands', flag: '🇳🇱' },
] as const;