# Generated by Django 4.2.28 on 2026-02-05 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_budgetcategory_budgetitem_projectbudget'),
        ('waterfall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterfallRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('business', 'Business'), ('resource', 'Resource'), ('external', 'External')], max_length=20)),
                ('probability', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('impact', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('analyzing', 'Analyzing'), ('mitigating', 'Mitigating'), ('closed', 'Closed')], default='identified', max_length=20)),
                ('owner', models.CharField(max_length=255)),
                ('mitigation', models.TextField()),
                ('date_identified', models.DateField()),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waterfall_risks', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterfallIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('business', 'Business'), ('resource', 'Resource'), ('process', 'Process')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in-progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('assignee', models.CharField(max_length=255)),
                ('reporter', models.CharField(max_length=255)),
                ('date_reported', models.DateField()),
                ('date_resolved', models.DateField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waterfall_issues', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterfallDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('phase', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('document', 'Document'), ('code', 'Code'), ('design', 'Design'), ('approval', 'Approval'), ('training', 'Training')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('review', 'Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('owner', models.CharField(max_length=255)),
                ('approver', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('acceptance_criteria', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waterfall_deliverables', to='projects.project')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='WaterfallBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_type', models.CharField(choices=[('scope', 'Scope Baseline'), ('schedule', 'Schedule Baseline'), ('cost', 'Cost Baseline')], max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('data', models.JSONField()),
                ('approved_by', models.CharField(max_length=255)),
                ('approval_date', models.DateField()),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waterfall_baselines', to='projects.project')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('project', 'baseline_type', 'version')},
            },
        ),
    ]
